[transport.ssh]
hostname = "106.110.32.96"
port = 22
username = "root"

[os]
name = "debian"
version = "bullseye"

[[devices]]
uri = "/dev/nvme0n1"
nsid = 1
labels = [ "dev", "bdev", "nvm", "scc" ]
driver_attachment = "kernel"

[[devices]]
uri = "/dev/nvme1n1"
nsid = 1
labels = [ "dev", "bdev", "nvm", "scc" ]
driver_attachment = "kernel"

[[devices]]
uri = "/dev/nvme2n1"
nsid = 1
labels = [ "dev", "bdev", "nvm", "scc" ]
driver_attachment = "kernel"

[[devices]]
uri = "/dev/nvme3n1"
nsid = 1
labels = [ "dev", "bdev", "nvm", "scc" ]
driver_attachment = "kernel"

[[devices]]
uri = "/dev/nvme4n1"
nsid = 1
labels = [ "dev", "bdev", "nvm", "scc" ]
driver_attachment = "kernel"

[[devices]]
uri = "/dev/nvme5n1"
nsid = 1
labels = [ "dev", "bdev", "nvm", "scc" ]
driver_attachment = "kernel"

[[devices]]
uri = "/dev/nvme6n1"
nsid = 1
labels = [ "dev", "bdev", "nvm", "scc" ]
driver_attachment = "kernel"

[[devices]]
uri = "/dev/nvme7n1"
nsid = 1
labels = [ "dev", "bdev", "nvm", "scc" ]
driver_attachment = "kernel"

[[devices]]
uri = "/dev/ng0n1"
nsid = 1
labels = [ "dev", "cdev", "nvm", "scc" ]
driver_attachment = "kernel"

[[devices]]
uri = "/dev/ng1n1"
nsid = 1
labels = [ "dev", "cdev", "nvm", "scc" ]
driver_attachment = "kernel"

[[devices]]
uri = "/dev/ng2n1"
nsid = 1
labels = [ "dev", "cdev", "nvm", "scc" ]
driver_attachment = "kernel"

[[devices]]
uri = "/dev/ng3n1"
nsid = 1
labels = [ "dev", "cdev", "nvm", "scc" ]
driver_attachment = "kernel"

[[devices]]
uri = "/dev/ng4n1"
nsid = 1
labels = [ "dev", "cdev", "nvm", "scc" ]
driver_attachment = "kernel"

[[devices]]
uri = "/dev/ng5n1"
nsid = 1
labels = [ "dev", "cdev", "nvm", "scc" ]
driver_attachment = "kernel"

[[devices]]
uri = "/dev/ng6n1"
nsid = 1
labels = [ "dev", "cdev", "nvm", "scc" ]
driver_attachment = "kernel"

[[devices]]
uri = "/dev/ng7n1"
nsid = 1
labels = [ "dev", "cdev", "nvm", "scc" ]
driver_attachment = "kernel"

[[devices]]
uri = "0000:41:00.0"
nsid = 1
labels = [ "dev", "pcie", "nvm", "scc" ]
driver_attachment = "userspace"

[[devices]]
uri = "0000:42:00.0"
nsid = 1
labels = [ "dev", "pcie", "nvm", "scc" ]
driver_attachment = "userspace"

[[devices]]
uri = "0000:43:00.0"
nsid = 1
labels = [ "dev", "pcie", "nvm", "scc" ]
driver_attachment = "userspace"

[[devices]]
uri = "0000:44:00.0"
nsid = 1
labels = [ "dev", "pcie", "nvm", "scc" ]
driver_attachment = "userspace"

[[devices]]
uri = "0000:45:00.0"
nsid = 1
labels = [ "dev", "pcie", "nvm", "scc" ]
driver_attachment = "userspace"

[[devices]]
uri = "0000:46:00.0"
nsid = 1
labels = [ "dev", "pcie", "nvm", "scc" ]
driver_attachment = "userspace"

[[devices]]
uri = "0000:47:00.0"
nsid = 1
labels = [ "dev", "pcie", "nvm", "scc" ]
driver_attachment = "userspace"

[[devices]]
uri = "0000:48:00.0"
nsid = 1
labels = [ "dev", "pcie", "nvm", "scc" ]
driver_attachment = "userspace"

[liburing.repository]
remote = "https://github.com/axboe/liburing.git"
path = "/root/git/liburing"
tag = "liburing-2.2"

[xnvme.repository]
remote = "https://github.com/OpenMPDK/xNVMe.git"
path = "/root/git/xnvme"
tag = "v0.6.0"

[xnvme.build]
type = "debug"

[spdk.repository]
remote = "https://github.com/safl/spdk.git"
path = "/root/git/spdk"
branch = "for_bdev_xnvme_v6"

[spdk.build]
prefix = "/opt/spdk"

[fio]
bin = "/opt/fio/bin/fio"

  [fio.repository]
  remote = "https://github.com/axboe/fio.git"
  path = "/root/git/fio"
  tag = "fio-3.32"

  [fio.build]
  prefix = "/opt/fio"

[fio.engines.libaio]
type = "builtin"

[fio.engines.io_uring]
type = "builtin"

[fio.engines.io_uring_cmd]
type = "builtin"

[fio.engines.xnvme]
path = "/usr/local/lib/x86_64-linux-gnu/libxnvme-fio-engine.so"
type = "external_dynamic"

[fio.engines.spdk_nvme]
path = "/root/git/spdk/build/fio/spdk_nvme"
type = "external_preload"

[fio.engines.spdk_bdev]
path = "/root/git/spdk/build/fio/spdk_bdev"
type = "external_preload"

[[duts]]
pcie = "0000:08:00.0"
os = "0n1"
sn = "PHBT718003QR016D"
label = "M10_16GB"

[[duts]]
pcie = "0000:09:00.0"
os = "1n1"
sn = "BTBT84921Y3W016N"
label = "M10_16GB"

[[duts]]
pcie = "0000:0a:00.0"
os = "2n1"
sn = "PHBT813407Z8016D"
label = "M10_16GB"

[[duts]]
pcie = "0000:41:00.0"
os = "3n1"
sn = "PHBT81350074016D"
label = "M10_16GB"

[[duts]]
pcie = "0000:42:00.0"
os = "4n1"
sn = "PHBT813407T8016D"
label = "M10_16GB"

[[duts]]
pcie = "0000:43:00.0"
os = "5n1"
sn = "PHBT813407ZW016D"
label = "M10_16GB"

[[duts]]
pcie = "0000:44:00.0"
os = "6n1"
sn = "PHBT81350076016D"
label = "M10_16GB"

[[duts]]
pcie = "0000:45:00.0"
os = "7n1"
sn = "PHBT813407U6016D"
label = "M10_16GB"

[[duts]]
pcie = "0000:46:00.0"
os = "8n1"
sn = "PHBT718003QW016D"
label = "M10_16GB"

[[duts]]
pcie = "0000:47:00.0"
os = "9n1"
sn = "BTBT84921FM7016N"
label = "M10_16GB"

[[duts]]
pcie = "0000:48:00.0"
os = "10n1"
sn = "PHBT8134068W016D"
label = "M10_16GB"
