[transport.ssh]
hostname = "106.110.32.91"
port = 22
username = "root"

[os]
name = "debian"
version = "bullseye"

[[devices]]
uri = "/dev/nvme0n1"
nsid = 1
labels = [ "dev", "bdev", "nvm", "scc" ]
driver_attachment = "kernel"

[[devices]]
uri = "/dev/nvme1n1"
nsid = 1
labels = [ "dev", "bdev", "nvm", "scc" ]
driver_attachment = "kernel"

[[devices]]
uri = "/dev/nvme2n1"
nsid = 1
labels = [ "dev", "bdev", "nvm", "scc" ]
driver_attachment = "kernel"

[[devices]]
uri = "/dev/nvme3n1"
nsid = 1
labels = [ "dev", "bdev", "nvm", "scc" ]
driver_attachment = "kernel"

[[devices]]
uri = "/dev/nvme4n1"
nsid = 1
labels = [ "dev", "bdev", "nvm", "scc" ]
driver_attachment = "kernel"

[[devices]]
uri = "/dev/nvme5n1"
nsid = 1
labels = [ "dev", "bdev", "nvm", "scc" ]
driver_attachment = "kernel"

[[devices]]
uri = "/dev/nvme6n1"
nsid = 1
labels = [ "dev", "bdev", "nvm", "scc" ]
driver_attachment = "kernel"

[[devices]]
uri = "/dev/nvme7n1"
nsid = 1
labels = [ "dev", "bdev", "nvm", "scc" ]
driver_attachment = "kernel"

[[devices]]
uri = "/dev/ng0n1"
nsid = 1
labels = [ "dev", "cdev", "nvm", "scc" ]
driver_attachment = "kernel"

[[devices]]
uri = "/dev/ng1n1"
nsid = 1
labels = [ "dev", "cdev", "nvm", "scc" ]
driver_attachment = "kernel"

[[devices]]
uri = "/dev/ng2n1"
nsid = 1
labels = [ "dev", "cdev", "nvm", "scc" ]
driver_attachment = "kernel"

[[devices]]
uri = "/dev/ng3n1"
nsid = 1
labels = [ "dev", "cdev", "nvm", "scc" ]
driver_attachment = "kernel"

[[devices]]
uri = "/dev/ng4n1"
nsid = 1
labels = [ "dev", "cdev", "nvm", "scc" ]
driver_attachment = "kernel"

[[devices]]
uri = "/dev/ng5n1"
nsid = 1
labels = [ "dev", "cdev", "nvm", "scc" ]
driver_attachment = "kernel"

[[devices]]
uri = "/dev/ng6n1"
nsid = 1
labels = [ "dev", "cdev", "nvm", "scc" ]
driver_attachment = "kernel"

[[devices]]
uri = "/dev/ng7n1"
nsid = 1
labels = [ "dev", "cdev", "nvm", "scc" ]
driver_attachment = "kernel"

[[devices]]
uri = "0000:41:00.0"
nsid = 1
labels = [ "dev", "pcie", "nvm", "scc" ]
driver_attachment = "userspace"

[[devices]]
uri = "0000:42:00.0"
nsid = 1
labels = [ "dev", "pcie", "nvm", "scc" ]
driver_attachment = "userspace"

[[devices]]
uri = "0000:43:00.0"
nsid = 1
labels = [ "dev", "pcie", "nvm", "scc" ]
driver_attachment = "userspace"

[[devices]]
uri = "0000:44:00.0"
nsid = 1
labels = [ "dev", "pcie", "nvm", "scc" ]
driver_attachment = "userspace"

[[devices]]
uri = "0000:45:00.0"
nsid = 1
labels = [ "dev", "pcie", "nvm", "scc" ]
driver_attachment = "userspace"

[[devices]]
uri = "0000:46:00.0"
nsid = 1
labels = [ "dev", "pcie", "nvm", "scc" ]
driver_attachment = "userspace"

[[devices]]
uri = "0000:47:00.0"
nsid = 1
labels = [ "dev", "pcie", "nvm", "scc" ]
driver_attachment = "userspace"

[[devices]]
uri = "0000:48:00.0"
nsid = 1
labels = [ "dev", "pcie", "nvm", "scc" ]
driver_attachment = "userspace"

[liburing.repository]
remote = "https://github.com/axboe/liburing.git"
path = "/root/git/liburing"
tag = "liburing-2.2"

[xnvme.repository]
remote = "https://github.com/karlowich/xNVMe.git"
path = "/root/git/xnvme"
branch = "0.7.0-for-spdk"

[xnvme.build]
type = "debug"

[spdk.repository]
remote = "https://github.com/karlowich/spdk.git"
path = "/root/git/spdk"
branch = "xnvme-0.7.0"

[spdk.build]
prefix = "/opt/spdk"

[fio]
bin = "/opt/fio/bin/fio"

  [fio.repository]
  remote = "https://github.com/axboe/fio.git"
  path = "/root/git/fio"
  tag = "fio-3.35"

  [fio.build]
  prefix = "/opt/fio"

[fio.engines.libaio]
type = "builtin"

[fio.engines.io_uring]
type = "builtin"

[fio.engines.io_uring_cmd]
type = "builtin"

[fio.engines.xnvme]
type = "builtin"

[fio.engines.spdk_nvme]
path = "/root/git/spdk/build/fio/spdk_nvme"
type = "external_preload"

[fio.engines.spdk_bdev]
path = "/root/git/spdk/build/fio/spdk_bdev"
type = "external_preload"

[[duts]]
pcie = "0000:01:00.0"
os = "0n1"
sn = "S69ENX0T810892F"
label = "980PRO_2TB"

[[duts]]
pcie = "0000:02:00.0"
os = "1n1"
sn = "S5GXNX0T875424D"
label = "980PRO_1TB"

[[duts]]
pcie = "0000:03:00.0"
os = "2n1"
sn = "S6WSNS0T207605K"
label = "980PRO_1TB"

[[duts]]
pcie = "0000:05:00.0"
os = "3n1"
sn = "S5GXNX0T811825D"
label = "980PRO_1TB"

[[duts]]
pcie = "0000:06:00.0"
os = "4n1"
sn = "S69ENX0T805102B"
label = "980PRO_2TB"

[[duts]]
pcie = "0000:07:00.0"
os = "5n1"
sn = "S69ENX0T805226J"
label = "980PRO_2TB"

[[duts]]
pcie = "0000:09:00.0"
os = "6n1"
sn = "S69ENX0T805189F"
label = "980PRO_2TB"

[[duts]]
pcie = "0000:0a:00.0"
os = "7n1"
sn = "S5GXNX0T875423K"
label = "980PRO_1TB"
